### ISSUE TITLE
Possible bug in shap.values

### ISSUE THREAD

**Issue by ramirogalvez** [liuyanguu/SHAPforxgboost#10]
Hello, I noticed that the "shap.values" function, which is heavily used in this package, has the following line.

`shap_contrib <- predict(xgb_model, as.matrix(X_train), predcontrib = TRUE, 
                                      approxcontrib = FALSE)`

Coercing the X_train matrix to a dense matrix by using as.matrix might lead to wrong behaviors in some cases. As it is detailed in the last bullet of this XGboost official documentation [page](https://github.com/dmlc/xgboost/blob/master/doc/faq.rst): "_it is important to use consistent data formats during training and scoring._". You can see other posts on the matter [here](https://stackoverflow.com/questions/46643584/xgboost-prediction-in-r-is-different-on-sparse-and-dense-matrices) and [here](https://github.com/dmlc/xgboost/issues/1634).

So if someone has trained a model using a sparte matrix (which is pretty common in XGBoost), and then provides the same model and exactly same matrix to shap.values (which is also pretty standard), it will coerce the matrix to a dense one before predicting shap scores, and that leads to inconsistent formats during training and scoring.

**Comment by liuyanguu** [comment]
Moreover, this is actually a well-known issue of the XGboost, and my old colleague @Kodiologist once wrote a blog [XGBoost, missing values, and sparsity](http://arfer.net/w/xgboost-sparsity) about it.

So how do I fix it, maybe I should just remove all the `as.matrix` since X_train used to fit the XGboost model should already be a matrix anyway?

@allanjust FYI as well.

**Comment by Kodiologist** [comment]
My position is that XGBoost's treatment of sparse 0s as missing is a bug, and thus you shouldn't use a sparse matrix to begin with.

**Comment by liuyanguu** [comment]
Good point! Thank you @Kodiologist

**Comment by ramirogalvez** [comment]
Hi, I read the @Kodiologist post, very interesting!

However, in the end, the role of shap values is to explain how models **actually** predict (even if they have an implementation bug). As it is, this actual function is missing that whenever a sparse matrix is used. I share the idea that removing `as.matrix` would solve this.
