### ISSUE TITLE
auto-select interesting color variable in dependence plots

### ISSUE THREAD

**Issue by mayer79** [liuyanguu/SHAPforxgboost#12]
A feature that I love in Python's shap package and that I miss in SHAPforxgboost is the following:

Dependence plots use a heuristic to automatically pick the (possibly) strongest interacting feature as `color_feature`. I don't know for sure how the heuristic is implemented (it does *not* use shap interaction). 
From a statistical point of view, we could pick the color feature that explains most vertical scatter in the dependence plot after binning non-discrete x and color features.

We could use `color_feature = "auto"` or a new argument like `color_feature_auto = TRUE` to enable this behaviour.

```r
library(SHAPforxgboost)
library(lightgbm)

X <- data.matrix(iris[, -1])
y <- iris[[1]]

fit <- lgb.train(
  params = list(objective = "regression"),
  data = lgb.Dataset(X, label = y),
  nrounds = 10, verbose = -2
)

shap <- shap.prep(fit, X_train = X)
# shap.plot.dependence(shap, x = "Sepal.Width", color_feature_auto = TRUE)
```

**Comment by liuyanguu** [comment]
That sounds a great idea @mayer79 , would you like to join as an author of the package and just revise it? I looped in @allanjust in case he has any comment on this. :)

**Comment by mayer79** [comment]
Definitively interested in joining you two! I could start by adding a vignette and draft above feature.

**Comment by liuyanguu** [comment]
Thank you @mayer79, really appreciate your help!
