### ISSUE TITLE
Any way to speed up SHAP interaction values?

### ISSUE THREAD

**Issue by Chrisjb** [liuyanguu/SHAPforxgboost#15]
When computing the interactions for use in dependence plots, we run:
```r
shap_int <- predict(xgb_mod, (X_train), predinteraction = TRUE)
```

This takes a really, really long time when the xgboost model has lots of variables. Do you know of any way of speeding up the calculation? Perhaps by only letting it consider features with high average importance?

Thanks for the great work

**Comment by liuyanguu** [comment]
I suggest refer to discussions at https://github.com/slundberg/shap
After all we just plot their results.

**Comment by Chrisjb** [comment]
Thanks, will do. I ended up building a smaller XGBoost model based on the top n variables from the original - less variables reduces compute time exponentially
