### ISSUE TITLE
Suggestion for shap.plot.summary()

### ISSUE THREAD

**Issue by aishameriane** [liuyanguu/SHAPforxgboost#21]
Hi!

I am using `shap.plot.summary()` and the values on the y-axis end up scrambled because of `geom_text()`:

```
plot1 <- ggplot(data = data_long) + 
              coord_flip(ylim = c(-x_bound, x_bound)) + 
              geom_hline(yintercept = 0) + 
              ggforce::geom_sina(aes(x = variable, y = value, color = stdfvalue), method = "counts", maxwidth = 0.7,  alpha = 0.7) + 
              geom_text(data = unique(data_long[, c("variable", "mean_value")]), aes(x = variable, y = -Inf, label = sprintf(label_format, 
    mean_value)), size = 3, alpha = 0.7, hjust = -0.2, fontface = "bold") + ...
```
My suggestion is to add `check_overlap = TRUE` to geom_text so there will be no overlap in the text.

**Comment by liuyanguu** [comment]
Many thanks for reporting the issue and for the great suggestion. I `check_overlap = TRUE` just hide some labels? Maybe we can try to make the font size smaller. If you could provide a reproducible example I can look further into it. It also depends on the size you use to print the plot.

**Comment by aishameriane** [comment]
Hi, @liuyanguu, thanks for the fast reply!

As far as I understood, the problem with `geom_text` is that it repeats the values over a dataset (even if they are the same), pasting over and over again, which creates the "blurry" aspect. Some people explained better than me in here: [link 1](https://stackoverflow.com/questions/10952832/ggplot2-is-there-a-fix-for-jagged-poor-quality-text-produced-by-geom-text) and [link 2](https://stackoverflow.com/questions/10952832/ggplot2-is-there-a-fix-for-jagged-poor-quality-text-produced-by-geom-text). 

For one-time annotations, the suggestion is to use `annotatate()` instead of `geom_text()`, but I couldn't make it work at least on my application. Then when I tried `check_overlap = TRUE` in the `geom_text()` options, it was just perfect.

Here are some images from my application:
1) Original graph with `shap.plot.summary()`: [Figure](https://github.com/aishameriane/Stuff/blob/master/Original_shap_plot.png)
2) Trying to reduce font size in `geom_text()` to `2` (instead of 3): [Figure](https://github.com/aishameriane/Stuff/blob/master/Rplot_lower_font.png)
3) Trying to increase font size in `geom_text()` to `4` (instead of 3): [Figure](https://github.com/aishameriane/Stuff/blob/master/Rplot_big_font.png)
4) Keepink the same font size, but using `check_overlap = TRUE`: [Figure](https://github.com/aishameriane/Stuff/blob/master/Rplot_check_overlap.png)

I put a code here, you should be able to reproduce the plot (the link for downloading the object for the plot is commented inside the code): https://github.com/aishameriane/Stuff/blob/master/Example_shap_plot_summary.r

**Comment by liuyanguu** [comment]
Many thanks @aishameriane I see what you mean. Indeed it was an issue that can be solved this way. I have added `check_overlap = TRUE` in the latest commit. Many thanks again.
