### ISSUE TITLE
What does the color gray mean in the summary plot?

### ISSUE THREAD

**Issue by MJimitater** [liuyanguu/SHAPforxgboost#23]
I ploted the shap summary using `shap.plot.summary(shap_long)`, but some dots are color gray, which however is not presented in the color legend. What does this mean?
![shap_plot](https://user-images.githubusercontent.com/26901261/145245279-f5188d17-9772-4a39-85a6-0f668f03f949.PNG)

**Comment by liuyanguu** [comment]
I think it's because the values plottings are outside of the range of the scale?

**Comment by MJimitater** [comment]
I thought the color scale is created by taking all the feature values into account.. how can it then be that some values are out of range?

**Comment by liuyanguu** [comment]
Please share a reproducible example so we can further check. Thank you.

**Comment by MJimitater** [comment]
After only showing the `top_n =  25`, no more gray points appeared
