### ISSUE TITLE
Annotation font family

### ISSUE THREAD

**Issue by flachboard** [liuyanguu/SHAPforxgboost#26]
Hello,

When I run the code below, all the font updates except for the annotated values. How can I update those as well?

```
shap.plot.summary(shap_retrec) +
  theme_ipsum(base_family = "Futura Medium") +
  theme(legend.position = "bottom") +
  ggtitle("Retail & Recreation Model")
```

![image](https://user-images.githubusercontent.com/22013957/155849271-6d3018c4-912e-48fc-b218-c65106f29fda.png)

**Comment by liuyanguu** [comment]
I have no idea. Have you figured it out? :)

**Comment by flachboard** [comment]
Lol, I have not. Thanks for the awesome package!
