### ISSUE TITLE
Error: could not find function "shap.summary_plot"

### ISSUE THREAD

**Issue by WivineBlekic** [liuyanguu/SHAPforxgboost#27]
Hello, 

I'm trying to plot my sharp values, however R cannot find the function `shap.summary_plot`, even when I try to force it by using `SHAPforxgboost::shap.summary_plot(shap_values)`. In this case, I have an error message saying  `'shap.summary_plot' is not an exported object from namespace :SHAPforxgboost`.

I am working on the R version 4.1.1 (2021-08-10).

Is the SHAPforxgboost package valid for this version ? What could I do ?

Thank you, 

Wivine Blekic.

**Comment by WivineBlekic** [comment]
Hello,

Even with shap.plot.summary I had the same issue. However, I found that it was the package “car” that did not install properly with the newer version of R and therefore SHAPforxgboost wasn’t fully installed. I solved the problem and plotted my Shap values !

Thanks for the quick answer,

Best regards,

Wivine.
________________________________
De : Yang Liu ***@***.***>
Envoyé : Tuesday, March 22, 2022 2:32:56 PM
À : liuyanguu/SHAPforxgboost ***@***.***>
Cc : Blekic, Wivine ***@***.***>; Author ***@***.***>
Objet : [EXTERNAL] Re: [liuyanguu/SHAPforxgboost] Error: could not find function "shap.summary_plot" (Issue #27)


I believe the function's name is shap.plot.summary, please see ?shap.plot.summary

**Comment by liuyanguu** [comment]
Great! Glad you figured it out!
