### ISSUE TITLE
Customizing point colors and variables range

### ISSUE THREAD

**Issue by rchemist0123** [liuyanguu/SHAPforxgboost#28]
First of all, thank you for creating this wonderful package.

I would like to make some suggestions for development of `SHAPforxgboost`.

**1. Customizing point colors function**
it would be very nice to change point gradients that users want, 
such as `scale_color_gradient(low='blue',  high='red')` .

**2. Selection of variables**
In my case, there were `mean_value<0` variables on my model, so I wanted to draw SHAP plots only with `mean_value>0` variables.
So, I hope users can select variables of models through `scale_x_discrete( )`.

Again, as a R user, thank you for this great package.

**Comment by liuyanguu** [comment]
Many thanks for your kind comments.
Since the output from e.g. `shap.plot.summary` is a ggplot2 object, you could just add extra layers, it will overwrite the old 
something like:
```
g1 <- shap.plot.summary(shap_long_iris)
g1 + scale_color_gradient(low='blue', high='red')
```
