### ISSUE TITLE
lightgbm support?

### ISSUE THREAD

**Issue by vspinu** [liuyanguu/SHAPforxgboost#3]
Thanks for the very useful package. 

Just like xgboost, lightgbm has an integrated SHAP functionality. Supporting both within the same package should be straightforward.

**Comment by liuyanguu** [comment]
Sorry I forgot to watch my own repo... Thank you for your very good advice. I will look into it.

**Comment by mayer79** [comment]
@liuyanguu : Since LightGBM is now stable on CRAN: should we add support for it? As @vspinu write, it is straightforward. I can make a pull request if you would agree.

**Comment by liuyanguu** [comment]
Thank you @mayer79. That sounds like a great idea. :)

**Comment by liuyanguu** [comment]
Really appreciate your help @mayer79 , thank you. I will upload to CRAN when the CRAN team is back from vacation next year.

**Comment by mayer79** [comment]
Sweet! We can test it with another 1-2 examples to see if things work smooth.
