### ISSUE TITLE
Contradicting LICENSE information

### ISSUE THREAD

**Issue by hclimente** [liuyanguu/SHAPforxgboost#38]
Hi,

There are two license files in this repository (LICENSE and LICENSE.md), with apparently contradicting information. Could you clarify which one is the valid one?

Thank you in advance!

**Comment by liuyanguu** [comment]
Many thanks for noticing that! I have removed the old (dup) one.

**Comment by hclimente** [comment]
Thanks for your prompt response! 

Please remember to update it also on CRAN (https://cran.r-project.org/web/packages/SHAPforxgboost/index.html). I think this ambiguity was the reason SHAPforxgboost is not included in conda-forge.
