### ISSUE TITLE
Request: implement factor-based comparison visualization (please!)

### ISSUE THREAD

**Issue by aruberuku** [liuyanguu/SHAPforxgboost#5]
I would like to take a list of factors, for example:
- clusters generated by force plot
- clusters derived from categorical segments
- clusters derived from summed SHAP values (i.e., proportional hazard ratio)
 
In all case, this would simply require the calculated SHAP score data set and an (optional) matching vector (data column). Charts would then be generated & segmented accordingly, per user direction.

For example: I would like to generate a pair of summary charts, one each for positive and negative cases as determined by summing SHAP values (i.e., based on whether the prop hazard is pos/neg).

This could be extended to show which features were most relevant wrt force plot-generated clusters.

Hope this wouldn't be too much trouble to implement!

Thanks,

**Comment by liuyanguu** [comment]
Thank you for the very good question. I am not sure what you mean .... You said "take a list of factors", do you mean the data is categorical? Could you share an example of the dataset you are work on, and the kind of visulization you would like to achieve?

**Comment by aruberutou** [comment]
Hi, thanks for the quick and positive response. Apologies for my many imprecisions.
Yes--I would like to create factor-based tabulations, where group means can be compared.
Manually, this is accomplished by taking the `.$shap_score` table and using `rbind()` to append one or several columns of factors. In the attached visualization, I created a binary column to indicate whether `rowSum()` was positive or negative, and then used that factor to create two separate tables.

![image](https://user-images.githubusercontent.com/18650337/73935569-1b3c4e80-48e1-11ea-9061-8aecc3acc266.png)

What I would like to do, is be able to create something conceptually similar via `shap.plot.summary`

Also: I just noticed that `shap.prep.stack.data` changes the row order, so that I cannot do the above. 
This sort of comparison is a key highlight in [a recent paper by Lundberg et al (2019)](https://arxiv.org/abs/1802.03888). 
![image](https://user-images.githubusercontent.com/18650337/73935827-c0572700-48e1-11ea-8fe8-3fcdfe4ca75f.png)

I hope you can implement--especially the issue regarding clusters. This is very exciting work and your contributions are enabling many new applications. Keep it up!

**Comment by liuyanguu** [comment]
Thank you for your kind words and detailed explanation! I kind of get what you mean, that stack plot is hard to replicate, I tried and ended up with `shap.plot.force_plot`, which indeed has room for improvement. I am not sure if what you want is a summary plot facet by a categorical variable like this? 
![sample_cat](https://user-images.githubusercontent.com/11966330/74077781-d8699c00-49f0-11ea-89f6-867671e2dbb6.png)
This one is easy as I only need to reorganize the long-format data from the SHAP values. But anyway we can work from the SHAP values output from `shap.values`, I guess it is just about how to present the SHAP values. 
If using `facet_wrap`, the order of variables are the same for the two plots. 
Here is the code for the plot above, basically it revised the `shap.prep` function. Is it the right direction?
```
suppressPackageStartupMessages({
library("SHAPforxgboost")
library("data.table")
library("ggplot2")
})

data("iris")
set.seed(123)
setDT(iris)
# set a categorical variable for example
iris$fakeCat <- 0
iris[sample(nrow(iris), nrow(iris)/2), fakeCat:=1]
X_train = as.matrix(iris[,c(colnames(iris)[1:4], "fakeCat"), with = FALSE])
mod1 = xgboost::xgboost(
  data = X_train, label = iris$Species, gamma = 0, eta = 1,
  lambda = 0, nrounds = 1, verbose = FALSE)

# shap.values(model, X_dataset) returns the SHAP
# data matrix and ranked features by mean|SHAP|
shap_values <- shap.values(xgb_model = mod1, X_train = X_train)
shap_contrib <- shap_values$shap_score
shap <- list(
  shap_score = shap_contrib,
  mean_shap_score = colMeans(abs(shap_contrib))[order(colMeans(abs(shap_contrib)), decreasing = T)]
)
std1 <- function(x){
  return ((x - min(x, na.rm = T))/(max(x, na.rm = T) - min(x, na.rm = T)))
}
# choose top n features
top_n <- dim(X_train)[2] # by default, use all features
# descending order
shap_score_sub <- setDT(shap$shap_score)[, names(shap$mean_shap_score)[1:top_n], with = F]
var_cat <- "fakeCat"
shap_score_long <- melt.data.table(shap_score_sub[,-..var_cat], measure.vars = colnames(shap_score_sub[,-..var_cat]))

# feature values: the values in the original dataset
# dayint is int, will throw a warning here
fv_sub <- as.data.table(X_train)[, names(shap$mean_shap_score)[1:top_n], with = F]
# standardize feature values
var_measure <- colnames(fv_sub)[colnames(fv_sub) != var_cat]
fv_sub_long <- melt.data.table(fv_sub, measure.vars = var_measure,
                               value.name = "rfvalue")

fv_sub_long[, stdfvalue := std1(rfvalue), by = "variable"]
# SHAP value: value
# raw feature value: rfvalue;
# standarized: stdfvalue
shap_long2 <- cbind(shap_score_long, fv_sub_long[,c('rfvalue','stdfvalue', var_cat), with = FALSE])
shap_long2[, mean_value := mean(abs(value)), by = variable]
setkey(shap_long2, variable)

# **SHAP summary plot**
shap.plot.summary(shap_long2, scientific = TRUE) +
  facet_wrap(~ fakeCat)

ggsave("sample_cat.png", width = 8, height = 4)
```

**Comment by liuyanguu** [comment]
I have included this option in the current version.
```
devtools::install_github("liuyanguu/SHAPforxgboost")

suppressPackageStartupMessages({
library("SHAPforxgboost")
library("data.table")
library("ggplot2")
})

data("iris")
# set a categorical variable for example
set.seed(123)
iris$Group <- 0
iris[sample(1:nrow(iris), nrow(iris)/2), "Group"] <- 1
X_train = as.matrix(setDT(iris)[,c(colnames(iris)[1:4], "Group"), with = FALSE])
mod1 = xgboost::xgboost(
  data = X_train, label = iris$Species, gamma = 0, eta = 1,
  lambda = 0, nrounds = 1, verbose = FALSE)

shap_long2 <- shap.prep(xgb_model = mod1, X_train = X_train, var_cat = "Group")
# **SHAP summary plot**
shap.plot.summary(shap_long2, scientific = TRUE) +
  facet_wrap(~ Group)
```

**Comment by aruberutou** [comment]
Wow. Absolutely amazing turn-around. Much appreciated! We can use this right away.

Can you add a similar `var_cat` function to `shap.prep.stack.data`. In my case, I would love to be able to include the original row id (order), so that I can match the generated clusters back to the original data. 

Thanks for the great work!

**Comment by liuyanguu** [comment]
No problem. Thank you for your very good advice. I have added an ID to the SHAP values 
Now `shap_long_iris ` from the code below and `force_plot_data` are linked by the same observation ID. This is an ID by rows of the SHAP matrix, i.e. 1:nrow(shap_values_iris)
```
library("SHAPforxgboost")
data("iris")
X1 = as.matrix(iris[,-5])
mod1 = xgboost::xgboost(
  data = X1, label = iris$Species, gamma = 0, eta = 1,
  lambda = 0, nrounds = 1, verbose = FALSE)

shap_values <- shap.values(xgb_model = mod1, X_train = X1)
shap_values_iris <- shap_values$shap_score
shap_long_iris <- shap.prep(shap_contrib = shap_values_iris, X_train = X1)

force_plot_data <- shap.prep.stack.data(shap_contrib = shap_values_iris,
                                  n_groups = 4)
```

The `shap.prep.stack.data` simply takes the `shap_values_iris`, and adds a clustering group using `hclust`. The `force_plot_data` has the same rows as the SHAP values, just reshuffled. So if you want to further revise the dataset, e.g. group by a categorical variable, it should be relatively easy.

**Comment by aruberutou** [comment]
Wow. You are an absolute hero. 
Thank you so very much for being so responsive. 
Very much looking forward to seeing how his all develops!

**Comment by liuyanguu** [comment]
Thank you for your kind words. Best wishes!
